import { normalizeAddress, validateConfig } from "./utils.js";
import type { AstalantyDeploymentFile, AstalantySDKConfig } from "./types.js";

/** Build SDK config from a deployment JSON generated by packages/contracts/scripts/deploy-mvp.cjs. */
export function configFromDeployment(
  deployment: AstalantyDeploymentFile,
  rpcUrl?: string
): AstalantySDKConfig {
  const config: AstalantySDKConfig = {
    network: {
      name: deployment.network,
      chainId: BigInt(deployment.chainId),
      ...(rpcUrl ? { rpcUrl } : {})
    },
    contracts: {
      mockUsdc: normalizeAddress(deployment.contracts.MockUSDC, "contracts.MockUSDC"),
      ausdToken: normalizeAddress(deployment.contracts.AUSDToken, "contracts.AUSDToken"),
      feeManager: normalizeAddress(deployment.contracts.AstalantyFeeManager, "contracts.AstalantyFeeManager"),
      paymaster: normalizeAddress(deployment.contracts.AstalantyPaymaster, "contracts.AstalantyPaymaster"),
      smartAccountFactory: normalizeAddress(
        deployment.contracts.AstalantySmartAccountFactory,
        "contracts.AstalantySmartAccountFactory"
      ),
      ...(deployment.contracts.AstalantySmartAccount
        ? {
            smartAccount: normalizeAddress(
              deployment.contracts.AstalantySmartAccount,
              "contracts.AstalantySmartAccount"
            )
          }
        : {})
    }
  };

  validateConfig(config);
  return config;
}
